module.exports = [
  "aceite",
  "cadena",
  "piñón",
  "corona",
  "filtro de aire",
  "filtro de aceite",
  "pastillas de freno",
  "disco de freno",
  "batería",
  "llanta delantera",
  "llanta trasera",
  "bombillo",
  "bobina",
  "carburador",
  "cdi",
  "piston",
  "cilindro",
  "embrague",
  "manubrio",
  "amortiguador",
  "espejo retrovisor",
  "guardabarros",
  "pedal de freno",
  "pedal de cambios",
  "tacómetro",
  "kit de arranque",
  "juego de empaques",
  "regulador de voltaje",
  "tapa de tanque",
  "cables de bujía",
  "bujía",
  "timón",
  "luces led moto"
];
